GET http://localhost:3000/places?text=av presidente vargas, belém, pa

###
GET http://localhost:3000/places?text=av almirante barroso, belém, pa

###
@originId=ChIJI0YoqZOOpJIRDOieW-TdAUI
@destinationId=ChIJG5DO4ImLpJIR24rTtRdf5fg

###
GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}

###
POST http://localhost:3000/routes
Content-Type: application/json

{
	"name": "Rota 10",
	"source_id": "{{ originId }}",
	"destination_id": "{{ destinationId }}"
}

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/6757f05669b353fdc3a6c242

###
# POST http://localhost:3000/routes/route-driver
# Content-Type: application/json

# {
# 	"route_id": "6757f05669b353fdc3a6c242",
# 	"lat": 111,
# 	"lng": 222
# }

